'use client'

import { useRef } from 'react'
import type { PlannerResults, SelectedItem } from '../types'
import { formatPrice } from '../utils/calculations'
import { CATEGORY_LABELS } from '../data/dietTemplates'

interface ResultsStepProps {
  results: PlannerResults
  weeklyBudget: number
  householdAdults: number
  onStartOver: () => void
}

export function ResultsStep({ results, weeklyBudget, householdAdults, onStartOver }: ResultsStepProps) {
  const listRef = useRef<HTMLDivElement>(null)
  const { totalPlanned, remaining, costPerDay, categoryBreakdown, prioritizedList } = results

  const handlePrint = () => {
    if (listRef.current) {
      const printWindow = window.open('', '_blank')
      if (!printWindow) return
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
          <head><title>Grocery List - FoodPulse</title>
          <style>
            body { font-family: system-ui, sans-serif; padding: 24px; max-width: 600px; margin: 0 auto; }
            h1 { font-size: 1.5rem; }
            .meta { color: #666; margin-bottom: 24px; }
            .priority { margin-top: 20px; }
            .priority h2 { font-size: 1rem; margin-bottom: 8px; }
            ul { list-style: none; padding: 0; }
            li { padding: 4px 0; border-bottom: 1px solid #eee; display: flex; justify-content: space-between; }
            .total { font-weight: bold; margin-top: 16px; }
          </style>
          </head>
          <body>
            <h1>🛒 Weekly Grocery List</h1>
            <div class="meta">
              Budget: ${formatPrice(weeklyBudget)} | Planned: ${formatPrice(totalPlanned)} | Remaining: ${formatPrice(remaining)}
            </div>
            <div class="priority">
              <h2>Priority 1 – Essentials</h2>
              <ul>${prioritizedList.priority1.map((i) => `<li><span>☐ ${i.name} (${i.quantity} ${i.unit})</span><span>${formatPrice(i.totalPrice)}</span></li>`).join('')}</ul>
            </div>
            <div class="priority">
              <h2>Priority 2 – Weekly fresh</h2>
              <ul>${prioritizedList.priority2.map((i) => `<li><span>☐ ${i.name} (${i.quantity} ${i.unit})</span><span>${formatPrice(i.totalPrice)}</span></li>`).join('')}</ul>
            </div>
            <div class="priority">
              <h2>Priority 3 – Nice to have</h2>
              <ul>${prioritizedList.priority3.map((i) => `<li><span>☐ ${i.name} (${i.quantity} ${i.unit})</span><span>${formatPrice(i.totalPrice)}</span></li>`).join('')}</ul>
            </div>
            <div class="total">Total: ${formatPrice(totalPlanned)}</div>
            <p style="margin-top: 24px; font-size: 12px; color: #888;">Generated by FoodPulse Grocery Budget Planner. Prices are estimates.</p>
          </body>
        </html>
      `)
      printWindow.document.close()
      printWindow.focus()
      printWindow.print()
      printWindow.close()
    }
  }

  return (
    <div className="p-6 md:p-8 space-y-8" ref={listRef}>
      <div>
        <h2 className="text-xl font-semibold text-neutral-900 mb-1">Your weekly grocery plan</h2>
        <p className="text-neutral-600 text-sm">Summary and prioritized list. Use Print to take it shopping.</p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <SummaryCard label="Budget" value={formatPrice(weeklyBudget)} sub="weekly" />
        <SummaryCard label="Planned" value={formatPrice(totalPlanned)} sub={`${weeklyBudget > 0 ? Math.round((totalPlanned / weeklyBudget) * 100) : 0}%`} />
        <SummaryCard label="Remaining" value={formatPrice(remaining)} sub={remaining >= 0 ? 'buffer' : 'over'} />
        <SummaryCard label="Cost/day" value={formatPrice(costPerDay)} sub={`per person (${householdAdults})`} />
      </div>

      {/* Category breakdown */}
      <div>
        <h3 className="font-semibold text-neutral-900 mb-4">Budget by category</h3>
        <div className="space-y-3">
          {categoryBreakdown.filter((c) => c.allocated > 0).map((c) => (
            <div key={c.category}>
              <div className="flex justify-between text-sm mb-1">
                <span className="text-neutral-700">{c.label}</span>
                <span className="text-neutral-600">
                  {formatPrice(c.spent)} / {formatPrice(c.allocated)} ({c.percentageUsed}%)
                </span>
              </div>
              <div className="h-2 bg-neutral-200 rounded-full overflow-hidden">
                <div
                  className="h-full bg-green-500 rounded-full transition-all"
                  style={{ width: `${Math.min(100, c.percentageUsed)}%` }}
                />
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Prioritized list */}
      <div>
        <h3 className="font-semibold text-neutral-900 mb-4">Prioritized shopping list</h3>
        <ListSection title="Priority 1 – Essentials (buy first)" items={prioritizedList.priority1} />
        <ListSection title="Priority 2 – Weekly fresh" items={prioritizedList.priority2} />
        <ListSection title="Priority 3 – Nice to have" items={prioritizedList.priority3} />
      </div>

      <p className="text-xs text-neutral-500">
        Prices are estimates based on US national averages. Verify at your store.
      </p>

      <div className="flex flex-wrap gap-4">
        <button
          type="button"
          onClick={handlePrint}
          className="px-6 py-3 bg-green-600 text-white font-semibold rounded-xl hover:bg-green-700 transition-colors"
        >
          Print list
        </button>
        <button
          type="button"
          onClick={onStartOver}
          className="px-6 py-3 border border-neutral-300 rounded-xl text-neutral-700 hover:bg-neutral-50 transition-colors"
        >
          Start over
        </button>
      </div>
    </div>
  )
}

function SummaryCard({ label, value, sub }: { label: string; value: string; sub: string }) {
  return (
    <div className="bg-neutral-50 rounded-xl p-4 border border-neutral-200">
      <p className="text-sm text-neutral-500">{label}</p>
      <p className="text-2xl font-bold text-neutral-900 mt-1">{value}</p>
      <p className="text-xs text-neutral-500 mt-1">{sub}</p>
    </div>
  )
}

function ListSection({ title, items }: { title: string; items: SelectedItem[] }) {
  if (items.length === 0) return null
  const total = items.reduce((s, i) => s + i.totalPrice, 0)
  return (
    <div className="mb-6">
      <div className="flex justify-between items-center mb-2">
        <h4 className="font-medium text-neutral-800">{title}</h4>
        <span className="text-sm text-neutral-600">{formatPrice(total)}</span>
      </div>
      <ul className="space-y-2">
        {items.map((item) => (
          <li
            key={item.id}
            className="flex justify-between items-center py-2 border-b border-neutral-100 text-sm"
          >
            <span className="text-neutral-800">
              ☐ {item.name} ({item.quantity} {item.unit})
            </span>
            <span className="font-medium text-green-700">{formatPrice(item.totalPrice)}</span>
          </li>
        ))}
      </ul>
    </div>
  )
}
